"""Orchestrates scraping, catalog storage, and meaning generation.

Two classes live here:

  LyricsPipeline – original orchestrator (scraper → DB → meaning generator)
  LyricsCatalog  – lightweight flat catalog seeded from saraga_carnatic with
                   on-demand Claude-powered meaning generation
"""

from __future__ import annotations

import os
import sqlite3
from datetime import datetime, timezone
from pathlib import Path

from carnatify.lyrics.database import LyricsDatabase
from carnatify.lyrics.meaning_generator import MeaningGenerator
from carnatify.schemas import LyricsEntry, MeaningEntry


def _scraper_imports():
    from carnatify.lyrics.scraper import SEED_COMPOSITION_PATHS, SEED_INDEX_PATHS, LyricsScraper
    return SEED_COMPOSITION_PATHS, SEED_INDEX_PATHS, LyricsScraper


class LyricsPipeline:
    """Wires scraper -> database -> meaning generator."""

    def __init__(
        self,
        database: LyricsDatabase | None = None,
        scraper: LyricsScraper | None = None,
        meaning_generator: MeaningGenerator | None = None,
    ):
        _, _, LyricsScraper = _scraper_imports()
        self.database = database or LyricsDatabase()
        self.scraper = scraper or LyricsScraper()
        self.meaning_generator = meaning_generator or MeaningGenerator()

    def lookup(
        self, composition_name: str
    ) -> tuple[LyricsEntry | None, MeaningEntry | None]:
        """Find a composition by name and return its lyrics + meaning."""
        matches = self.database.search_by_name(composition_name)
        if not matches:
            return None, None
        entry = matches[0]
        meaning = self.meaning_generator.generate(entry)
        return entry, meaning

    def build_catalog(
        self,
        composition_paths: list[str] | None = None,
        index_paths: list[str] | None = None,
    ) -> int:
        """Scrape compositions (seed list + discovered links) into the database.

        Returns the number of entries written.
        """
        SEED_COMPOSITION_PATHS, SEED_INDEX_PATHS, _ = _scraper_imports()
        paths = list(composition_paths or SEED_COMPOSITION_PATHS)
        for index_path in index_paths or SEED_INDEX_PATHS:
            try:
                paths.extend(self.scraper.discover_composition_links(index_path))
            except Exception:
                continue

        seen: set[str] = set()
        deduped = [p for p in paths if not (p in seen or seen.add(p))]

        count = 0
        for entry in self.scraper.scrape_catalog(deduped):
            self.database.insert(entry)
            count += 1
        return count

    def generate_all_meanings(self, force: bool = False) -> int:
        """Generate (and cache) meanings for every catalog entry.

        Returns the number of meanings generated or already cached.
        """
        count = 0
        for entry in self.database.list_all():
            self.meaning_generator.generate(entry, force=force)
            count += 1
        return count


# ── Flat lyrics catalog ───────────────────────────────────────────────────────

_SARAGA_DATA_HOME = "/Users/shyamravidath/carnatify"

_CATALOG_SCHEMA = """
CREATE TABLE IF NOT EXISTS lyrics_catalog (
    title                TEXT PRIMARY KEY,
    composer             TEXT NOT NULL DEFAULT '',
    raga                 TEXT NOT NULL DEFAULT '',
    language             TEXT NOT NULL DEFAULT '',
    lyrics_original      TEXT NOT NULL DEFAULT '',
    meaning_en           TEXT,
    meaning_generated_at TEXT
);
"""


class LyricsCatalog:
    """Flat SQLite catalog of Carnatic composition titles, metadata, and meanings.

    Schema
    ------
    title                – composition name (primary key)
    composer             – composer name (populated if known; empty stub otherwise)
    raga                 – raga name from saraga metadata
    language             – language of the lyrics (empty until enriched)
    lyrics_original      – original-language lyrics text (empty until enriched)
    meaning_en           – English meaning generated by Claude (NULL until requested)
    meaning_generated_at – ISO-8601 UTC timestamp of last generation
    """

    def __init__(self, db_path: str | Path | None = None):
        if db_path is None:
            from carnatify.config import PROJECT_ROOT
            db_path = PROJECT_ROOT / "data" / "lyrics.db"
        self.db_path = Path(db_path)
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        self._conn = sqlite3.connect(str(self.db_path))
        self._conn.row_factory = sqlite3.Row
        self._conn.executescript(_CATALOG_SCHEMA)
        self._conn.commit()

    def close(self) -> None:
        self._conn.close()

    def __enter__(self) -> LyricsCatalog:
        return self

    def __exit__(self, *exc) -> None:
        self.close()

    # -- seeding --------------------------------------------------------------

    def seed_from_saraga(self, data_home: str = _SARAGA_DATA_HOME) -> int:
        """Insert stub rows for saraga compositions not already in the catalog.

        Pulls title and raga from the saraga_carnatic mirdata loader. Composer
        and lyrics fields are left empty — they can be filled in later. Does NOT
        call the Anthropic API.

        Returns the number of new rows inserted.
        """
        import mirdata

        saraga = mirdata.initialize("saraga_carnatic", data_home=data_home)

        seen: set[str] = set()
        stubs: list[tuple] = []

        for tid in saraga.track_ids:
            t = saraga.track(tid)
            meta = t.metadata or {}

            work = meta.get("work") or []
            title = work[0]["title"] if work else meta.get("title", "")
            if not title or title in seen:
                continue
            seen.add(title)

            raaga_list = meta.get("raaga") or []
            raga = ""
            if raaga_list:
                r = raaga_list[0]
                # prefer romanized common_name; fall back to diacritical name
                raga = r.get("common_name") or r.get("name", "")

            stubs.append((title, "", raga, "", "", None, None))

        cur = self._conn.executemany(
            """
            INSERT OR IGNORE INTO lyrics_catalog
                (title, composer, raga, language, lyrics_original,
                 meaning_en, meaning_generated_at)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            stubs,
        )
        self._conn.commit()
        return cur.rowcount

    def seed_from_scrape(self, records: list[dict]) -> int:
        """Insert stub rows for scraped (title, raga) compositions.

        Accepts records shaped like ``{"title", "raga", "artist", "source_url"}``
        (as produced by ``scrape_concerts.py``). Only title and raga are stored;
        composer and lyrics are left empty for later enrichment. Uses
        ``INSERT OR IGNORE`` so existing titles are untouched, and does NOT call
        the Anthropic API.

        Returns the number of new rows inserted.
        """
        seen: set[str] = set()
        stubs: list[tuple] = []

        for rec in records:
            title = (rec.get("title") or "").strip()
            if not title or title in seen:
                continue
            seen.add(title)

            raga = (rec.get("raga") or "").strip()
            stubs.append((title, "", raga, "", "", None, None))

        cur = self._conn.executemany(
            """
            INSERT OR IGNORE INTO lyrics_catalog
                (title, composer, raga, language, lyrics_original,
                 meaning_en, meaning_generated_at)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            stubs,
        )
        self._conn.commit()
        return cur.rowcount

    # -- meaning generation ---------------------------------------------------

    def generate_meaning(self, title: str) -> str | None:
        """Return an English meaning for *title*, generating it if not cached.

        Calls the Gemini API (gemini-2.0-flash) on first request, then
        stores the result so subsequent calls are instant. Skips the API if a
        meaning is already stored.

        Requires GEMINI_API_KEY to be set in the environment.

        Returns the meaning string, or None if *title* is not in the catalog.
        """
        row = self._conn.execute(
            "SELECT * FROM lyrics_catalog WHERE title = ?", (title,)
        ).fetchone()

        if row is None:
            return None

        if row["meaning_en"]:
            return row["meaning_en"]

        import google.generativeai as genai

        genai.configure(api_key=os.environ["GEMINI_API_KEY"])

        raga = row["raga"] or "an unspecified raga"
        composer = row["composer"]
        lyrics = row["lyrics_original"]

        if lyrics:
            user_msg = (
                f"Carnatic composition: '{title}'"
                + (f" by {composer}" if composer else "")
                + f", set in raga {raga}.\n\n"
                f"Lyrics:\n{lyrics}\n\n"
                "Give a brief English meaning and cultural context."
            )
        else:
            composer_clause = f", composed by {composer}" if composer else ""
            user_msg = (
                f"The Carnatic composition '{title}'{composer_clause} is set in "
                f"raga {raga}. Provide a brief English meaning and cultural context: "
                "what emotional sentiment or devotional theme it likely expresses, "
                "the deity or subject being addressed, and any notable character of "
                "this raga in Carnatic tradition. Keep it to 2-3 short paragraphs."
            )

        model = genai.GenerativeModel(
            "gemini-2.5-flash",
            system_instruction=(
                "You are a scholar of Carnatic music and its devotional poetry. "
                "Explain compositions clearly for a general audience. "
                "Write in plain English — no headers, no bullet points."
            ),
        )
        response = model.generate_content(user_msg)
        meaning = response.text.strip()

        self._conn.execute(
            """
            UPDATE lyrics_catalog
               SET meaning_en = ?, meaning_generated_at = ?
             WHERE title = ?
            """,
            (meaning, datetime.now(timezone.utc).isoformat(), title),
        )
        self._conn.commit()
        return meaning

    # -- lookup ---------------------------------------------------------------

    def lookup(self, title: str) -> dict | None:
        """Return the full catalog row for *title*, or None if not found.

        Tries an exact match first, then a case-insensitive partial match.
        """
        row = self._conn.execute(
            "SELECT * FROM lyrics_catalog WHERE title = ?", (title,)
        ).fetchone()
        if row is None:
            row = self._conn.execute(
                "SELECT * FROM lyrics_catalog WHERE title LIKE ? ORDER BY title LIMIT 1",
                (f"%{title}%",),
            ).fetchone()
        return dict(row) if row else None
